# Generated by Django 2.0.4 on 2018-04-25 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='user',
            new_name='user_id',
        ),
    ]
