# Generated by Django 2.0.4 on 2018-04-27 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20180427_0703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='voted',
        ),
        migrations.AddField(
            model_name='voted',
            name='question',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
            preserve_default=False,
        ),
    ]
